cache:
  mount:
    - node_modules
    - docker/image.tar

build:
  image: reddit/reddit-nodejs:latest
  pull: true
  commands:
    - npm install
    - npm run build
    - npm run lint
    - npm run test

publish:
  docker:
    username: $$DOCKERHUB_USERNAME
    password: $$DOCKERHUB_PASSWORD
    email: sysops@reddit.com
    repo: reddit/reddit-mobile
    tag: $$BRANCH
    file: Dockerfile.staging
    # Image layer caching.
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: $$BRANCH

notify:
  slack:
    webhook_url: $$CI_SLACK_WEBHOOK_URL
    channel: ci-notifications
#  slack:
#    webhook_url: $$CI_SLACK_WEBHOOK_URL
#    repo: reddit/reddit-mobile
#    channel: frontend-platform
