publish:
  docker:
    username: $$DOCKERHUB_USERNAME
    password: $$DOCKERHUB_PASSWORD
    email: sysops@reddit.com
    repo: reddit/reddit-mobile
    tag: $$BRANCH
    file: Dockerfile.staging
    # Image layer caching.
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: $$BRANCH

# These plugins are triggered after a build failure/success.
notify:
  slack:
    webhook_url: $$CI_SLACK_WEBHOOK_URL
    channel: ci-notifications

cache:
  mount:
    - docker/image.tar
